version: "2"

services:
  grafana:
    image: grafana/grafana:7.0.4
    expose:
      - "3000"
    ports:
      - "13000:3000"
    volumes:
      - "./grafana/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yml"
      - "./grafana/dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml"
      - "./grafana/leetcode_dashboard.json:/etc/grafana/provisioning/dashboards/leetcode_dashboard.json"
    networks:
      backend:

  prometheus:
    image: prom/prometheus:v2.20.1
    expose:
      - "9090"
    ports:
      - "19090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      backend:
        aliases:
          - prometheus.service.com

  app:
    image: eshishkin/leetcode-dashboard:latest
    mem_limit: 128m
    expose:
      - "8080"
    ports:
      - "18080:8080"
    networks:
      backend:
        aliases:
          - leetcode-dashboard.service.com

networks:
  backend:
