global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'leetcode-dashboard-metrics'

    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['leetcode-dashboard.service.com:8080']