global:
  scrape_interval: 15s


scrape_configs:
  - job_name: 'leetcode-dashboard-metrics'

    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['leetcode-dashboard.service.com:8080']

  - job_name: 'eshishkin-profile-metrics'

    scrape_interval: 3600s
    metrics_path: /profile/eshishkin/metrics
    static_configs:
      - targets: ['leetcode-dashboard.service.com:8080']

  - job_name: 'ocmwdt-profile-metrics'

    scrape_interval: 3600s
    metrics_path: /profile/ocmwdt/metrics
    static_configs:
      - targets: ['leetcode-dashboard.service.com:8080']