{
 "title": "Leetcode",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Acceptance Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "leetcode_accepted/leetcode_submitted",
     "legendFormat": "{{profile}}"
    }
   ]
  },
  {
   "title": "Submissions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "leetcode_submitted", "legendFormat": "{{profile}}" }
   ]
  },
  {
   "title": "Solved Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "leetcode_solved", "legendFormat": "{{profile}}" }
   ]
  }
 ]
}